version: '3.8'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api
    image: api
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - vocab_network